export const COURSE_SAVE_START = 'COURSE_SAVE_START';
export const COURSE_SAVE_SUCCESS = 'COURSE_SAVE_SUCCESS';
export const COURSE_SAVE_FAILURE = 'COURSE_SAVE_FAILURE';


export const AUTH_SAVE_START = 'AUTH_SAVE_START';
export const AUTH_SAVE_SUCCESS = 'AUTH_SAVE_SUCCESS';
export const AUTH_SAVE_FAILURE = 'AUTH_SAVE_FAILURE';
